version: '3'
services:
  web:
    command: bash -c "scripts/init-app.sh /dev/stderr && cd app && gunicorn -k gevent -b 0.0.0.0:80 services.api.wsgi:application"
    build:
      context: .
      dockerfile: ./app/docker/Dockerfile.dev
    env_file:
      - ./app/config
    volumes:
      - .:/app
    ports:
      - "5120:80"
