version: '3'
services:
  api:
    entrypoint: start-ce
    image: cenv
    build:
      context: .
      dockerfile: app/Dockerfile
    env_file: ./config/pg.credentials
    volumes:
      - ./app:/usr/local/share/cenv
      - ./data:/var/local/cenv
    ports:
      - "5123:5123"
  data:
    image: postgres:11
    restart: always
    env_file: ./config/pg.credentials
    volumes:
      - app-data:/var/lib/postgresql
    ports:
      - "5432:5432"
volumes:
  app-data:
    external: false