---

# Who owns the serial console logs in console_log_path
libvirt_vm_log_owner: qemu

# The environment passed to virt_volume.sh
libvirt_vm_volume_creation_env:
  VOLUME_GROUP: qemu
  VOLUME_OWNER: qemu
