#
# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
server_name: 'mcp-kubernetes-dev'
box_name: 'ubuntu/bionic64'
cpus: 2
memory_size: 2048
copy_gitconfig: true
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false