#
# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
dev_box_name: "ubuntu/bionic64"
node_box_name: "generic/ubuntu1804"
os: "ubuntu-18.04"
user: "vagrant"
password: "vagrant"
network_bridge: "eth0"
cpus: 1
memory_size: 2048
copy_gitconfig: true
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
api_port: 5120

dev_hostname: "dev"
dev_ip: "172.16.50.199"

masters: 2
master_1_hostname: "master-1"
master_1_ip: "172.16.50.200"
master_1_etcd: true

master_2_hostname: "master-2"
master_2_ip: "172.16.50.201"
master_2_etcd: true

nodes: 2
node_1_hostname: "node-1"
node_1_ip: "172.16.50.202"
node_1_etcd: true

node_2_hostname: "node-2"
node_2_ip: "172.16.50.203"
node_2_etcd: false
