#
# This file contains default settings for the Vagrant development environment.
#
# If you need to override any of these configurations on your own platform then
# copy this file into a "config.yml" in the vagrant directory
# (directory of this file) and your overrides will take effect on the next
# vagrant up or reload.
#
hostname: "zimagi"
box_name: "ubuntu/focal64"
user: "vagrant"
cpus: 1
memory_size: 2048
share_lib: true
copy_vimrc: false
copy_profile: false
copy_bash_aliases: false
copy_bashrc: false
command_port: 5123
data_port: 5323
db_port: 5432
queue_port: 6379
http_port: 8000
time_zone: "America/New_York"
default_modules: []
