version: 2

certs: &certs
  name: Updating certificates
  command: |
    mkdir -p ./certs
    ./scripts/store-cert.py ./certs/cenv-ca.key "$CENV_CA_KEY"
    ./scripts/store-cert.py ./certs/cenv-ca.crt "$CENV_CA_CERT"
    ./scripts/store-cert.py ./certs/cenv.key "$CENV_KEY"
    ./scripts/store-cert.py ./certs/cenv.crt "$CENV_CERT"

jobs:
  deploy-docker-latest:
    machine: true
    steps:
      - checkout
      - run: *certs
      - run:
          name: Deploy latest Docker image
          command: |
            ./packages/docker/deploy_latest.sh

  deploy-docker-version:
    machine: true
    steps:
      - checkout
      - run: *certs
      - run:
          name: Deploy versioned Docker image
          command: |
            ./packages/docker/deploy_version.sh

  deploy-pip:
    docker:
    - image: python:3.6
    steps:
      - checkout
      - run:
          name: Deploy Pip package
          command: |
            ./packages/pip/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker-latest:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
      - deploy-docker-version:
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
      - deploy-pip:
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
