version: 2

certs: &certs
  name: Updating certificates
  command: |
    ./app/scripts/store-cert.py ./app/certs/cenv-ca.key "$CENV_CA_KEY"
    ./app/scripts/store-cert.py ./app/certs/cenv-ca.crt "$CENV_CA_CERT"
    ./app/scripts/store-cert.py ./app/certs/cenv.key "$CENV_KEY"
    ./app/scripts/store-cert.py ./app/certs/cenv.crt "$CENV_CERT"

jobs:
  deploy-docker:
    machine: true
    steps:
      - checkout
      - run: *certs
      - run:
          name: Deploy Docker image
          command: |
            ./packages/docker/deploy.sh
  
  deploy-pip:
    docker:
    - image: python:3.6
    steps:
      - checkout
      - run:
          name: Deploy Pip package
          command: |
            ./packages/pip/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker:
          filters:
            tags:
              only: /^.*/
#            branches:
#              ignore: /.*/
      - deploy-pip:
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
