version: 2

certs: &certs
  name: Updating certificates
  command: |
    echo "$CENV_CA_KEY" | sed 's/\s\+/\n/g' > ./app/certs/cenv-ca.key
    #echo "$CENV_CA_KEY" | tr " " "\n" > ./app/certs/cenv-ca.key
    echo "$CENV_CA_CERT" | tr " " "\n" > ./app/certs/cenv-ca.crt
    #echo "$CENV_KEY" | tr " " "\n" > ./app/certs/cenv.key
    #echo "$CENV_CERT" | tr " " "\n" > ./app/certs/cenv.crt

jobs:
  deploy-docker:
    machine: true
    steps:
      - checkout
      - run: *certs
      - run:
          name: Deploy Docker image
          command: |
            ./packages/docker/deploy.sh
  
  deploy-pip:
    docker:
    - image: python:3.6
    steps:
      - checkout
      - run:
          name: Deploy Pip package
          command: |
            ./packages/pip/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-docker:
          filters:
            tags:
              only: /^.*/
#            branches:
#              ignore: /.*/
      - deploy-pip:
          filters:
            tags:
              only: /^.*/
            branches:
              ignore: /.*/
