plugins:
    base:
        interface:
            provider_config:
                params:
                    type: str
    data:
        base: base
        interface:
            facade:
                return: "@systems.models.facade.Facade"
            initialize_instances:
            initialize_instance:
                params:
                    instance: "@systems.models.base.BaseModel"
                    created: bool
            prepare_instance:
                params:
                    instance: "@systems.models.base.BaseModel"
                    created: bool
            store_related:
                params:
                    instance: "@systems.models.base.BaseModel"
                    created: bool
                    test: bool
            finalize_instance:
                params:
                    instance: "@systems.models.base.BaseModel"

    meta:
        base: base
        interface:
            register_types:

    task:
        base: base
        interface:
            get_fields:
                returns: dict
            execute:
                params:
                    results: "@plugins.task.TaskResult"
                    params: dict
