version: '3'
services:
  api:
    entrypoint: start-ce
    image: mcmi/mcmi
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - MCMI_LOG_LEVEL=debug
      - MCMI_POSTGRES_HOST=data
      - MCMI_POSTGRES_PORT=5432
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/mcmi:/usr/local/share/mcmi
      - /var/local/mcmi.server:/var/local/mcmi
      - /usr/local/lib/mcmi:/usr/local/lib/mcmi
    ports:
      - "5123:5123"

  data:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${MCMI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MCMI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MCMI_POSTGRES_DB}
    volumes:
      - app-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  app-data:
    external: false