version: '3'
services:
  api:
    entrypoint: start-mcmi
    image: mcmi/mcmi
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - MCMI_LOG_LEVEL=debug
      - MCMI_POSTGRES_HOST=data
      - MCMI_POSTGRES_PORT=5432
      - MCMI_REDIS_HOST=queue
      - MCMI_REDIS_PORT=6379
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/mcmi:/usr/local/share/mcmi
      - /var/local/mcmi.server:/var/local/mcmi
      - /usr/local/lib/mcmi:/usr/local/lib/mcmi
    ports:
      - "5123:5123"

  data:
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_USER: ${MCMI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MCMI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MCMI_POSTGRES_DB}
    volumes:
      - app-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  queue:
    image: redis:5.0
    restart: always
    command: redis-server --requirepass ${MCMI_REDIS_PASSWORD}
    volumes:
      - app-tasks:/data
    ports:
      - "6379:6379"

volumes:
  app-data:
    external: false

  app-tasks:
    external: false