version: '3'
services:
  api:
    entrypoint: start-ce
    image: cenv/cenv:latest
    restart: always
    environment:
      - POSTGRES_HOST=data
      - POSTGRES_PORT=5432
    env_file:
      - /var/local/cenv/django.env
      - /var/local/cenv/pg.credentials.env
    volumes:
      - /usr/local/lib/cenv:/usr/local/lib/cenv
    ports:
      - "5123:5123"
  data:
    image: postgres:11
    restart: always
    env_file: /var/local/cenv/pg.credentials.env
    volumes:
      - /var/local/cenv:/var/lib/postgresql
    ports:
      - "5432:5432"
