version: '3'
services:
  api:
    entrypoint: start-ce
    image: ${CENV_DEFAULT_RUNTIME_IMAGE}
    restart: always
    env_file: system.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/lib/cenv:/usr/local/lib/cenv
    ports:
      - "5123:5123"
