version: '3'
services:
  api:
    entrypoint: start-ce
    image: ${MCMI_DEFAULT_RUNTIME_IMAGE}
    restart: always
    environment:
      - MCMI_POSTGRES_HOST=data
      - MCMI_POSTGRES_PORT=5432
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/lib/mcmi:/usr/local/lib/mcmi
    ports:
      - "5123:5123"

  data:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${MCMI_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MCMI_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MCMI_POSTGRES_DB}
    volumes:
      - /var/local/data/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
