version: '3'
services:
  api:
    entrypoint: start-ce
    image: cenv/cenv
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - CENV_DEBUG=True
      - CENV_LOG_LEVEL=debug
      - CENV_POSTGRES_HOST=data
      - CENV_POSTGRES_PORT=5432
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/share/cenv:/usr/local/share/cenv
      - /var/local/cenv.server:/var/local/cenv
      - /usr/local/lib/cenv.server:/usr/local/lib/cenv
    ports:
      - "5123:5123"

  data:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: ${CENV_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CENV_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CENV_POSTGRES_DB}
    volumes:
      - app-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  app-data:
    external: false