extensions:
    environment:
        base: resource
        mixins: [ provider ]
        id: name
        packages: []
        fields:
            repo:
                type: char
                options:
                    max_length: 256
                    default: "@settings.DEFAULT_RUNTIME_REPO"
            base_image:
                type: char
                options:
                    max_length: 256
                    default: "@settings.DEFAULT_RUNTIME_IMAGE"
            runtime_image:
                type: char
                options:
                    "null": true
                    max_length: 256
        meta:
            dynamic_fields: [ is_active ]

    host:
        base: environment
        packages: [ host ]
        fields:
        host:
            type: url
        port:
            type: int
            options:
                default: 5123
        user:
            type: char
            options:
                max_length: 150
                default: "@settings.ADMIN_USER"
        token:
            type: encrypted_char
            options:
                max_length: 256
                default: "@settings.DEFAULT_ADMIN_TOKEN"