---
# The destroyed state does not seem to be idempotent, so check whether the VM
# exists before destroying it.
- name: Check the VM's status
  virt:
    name: "{{ vm.name }}"
    command: list_vms
  register: result
  become: yes

- block:
    - name: Ensure the VM is absent
      virt:
        name: "{{ vm.name }}"
        state: destroyed
      become: yes

    - name: Ensure the VM is undefined
      virt:
        name: "{{ vm.name }}"
        command: undefine
      become: yes
  when: vm.name in result.list_vms
