plugin_mixins:
    cli_task:
        class: CLITaskMixin
        option:
            env:
                type: dict
                default: {}
                help: "Environment variables to pass to executable"
    csv_source:
        class: CSVSourceMixin
