---
- hosts: all
  roles:
    - { role: system-core }
    - { role: dev-sec.os-hardening }
    - { role: dev-sec.ssh-hardening }
    - { role: geerlingguy.ntp }
  vars:
    admin_user: admin
    sysctl_config:
      net.ipv4.ip_forward: 1
      net.ipv6.conf.all.forwarding: 1
    ufw_manage_defaults: true
    ufw_default_input_policy: 'ACCEPT'
    ufw_default_forward_policy: 'ACCEPT'
    ssh_allow_users: admin
    ssh_client_password_login: false
    ssh_server_password_login: false
    ntp_enabled: true
    ntp_manage_config: true
    ntp_timezone: EST

- name: Include Kubernetes tasks
  include: kubespray/cluster.yml
  vars:
    kubelet_max_pods: 200
    use_docker_engine: true

#- hosts: masters[0]
#  roles:
#    - { role: nfs-mount }
#    - { role: fupelaqu.docker-registry }
#  vars:
#    nfs_share_mounts:
#      - path: /var/lib/docker-registry
#        location: 10.0.20.10:/volume1/registry
#        opts: "{{ nfs_mount_opts }},rw,sync"
#    docker_registry_users:
#      - name: docker
#        password: changeit
