---
- hosts: all
  roles:
    - { role: system-core }
    - { role: dev-sec.ssh-hardening }
  vars:
    admin_user: admin
    ssh_allow_users: admin
    ssh_client_password_login: false
    ssh_server_password_login: false

- name: Include Kubernetes tasks
  include: ../kubespray/cluster.yml
  vars:
    kubelet_max_pods: 200
    use_docker_engine: true
    artifacts_dir: "../config"
